const projectInfo = [{
  id: 0,
  featureImg: 'images/project-img1.png',
  projectName: 'Space Travelers',
  technologies: ['HTML', 'SCSS', 'React & Redux', 'Javascript'],
  description: 'The Space-Travelers app is a single-page-app that gets information from the SpaceX API and shows you a list with some of their rockets and missions for you to reserve, join and watch at your profile page.',
  liveBtn: 'https://salty-coast-56792.herokuapp.com/',
  sourceBtn: 'https://github.com/ulisesedu7/microverse-space-travelers',
},
{
  id: 1,
  featureImg: 'images/project-img2.png',
  projectName: 'Math Magicians',
  technologies: ['HTML', 'CSS', 'Javascript', 'React'],
  description: 'This small web application built with React.js helps you with small calculations, a simple calculator that proves just how powerful and easy can React be when creating single-page-apps.',
  liveBtn: 'https://mysterious-bayou-66250.herokuapp.com/',
  sourceBtn: 'https://github.com/ulisesedu7/Math-Magicians',
},
{
  id: 2,
  featureImg: 'images/project-img3.svg',
  projectName: 'Project 3',
  technologies: ['Ruby on Rails', 'CSS', 'HTML', 'Javascript'],
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum',
  liveBtn: 'https://google.com',
  sourceBtn: 'https://google.com',
},
{
  id: 3,
  featureImg: 'images/project-img4.svg',
  projectName: 'Project 4',
  technologies: ['Ruby on Rails', 'CSS', 'HTML', 'Javascript'],
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum',
  liveBtn: 'https://google.com',
  sourceBtn: 'https://google.com',
},
{
  id: 4,
  featureImg: 'images/project-img5.svg',
  projectName: 'Project 5',
  technologies: ['Ruby on Rails', 'CSS', 'HTML', 'Javascript'],
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum',
  liveBtn: 'https://google.com',
  sourceBtn: 'https://google.com',
},
{
  id: 5,
  featureImg: 'images/project-img6.svg',
  projectName: 'Project 6',
  technologies: ['Ruby on Rails', 'CSS', 'HTML', 'Javascript'],
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsu',
  liveBtn: 'https://google.com',
  sourceBtn: 'https://google.com',
}];

export default projectInfo;