const projectInfo = [{
  id: 0,
  featureImg: 'images/project-img1.png',
  projectName: 'Space Travelers',
  technologies: ['HTML', 'SCSS', 'React & Redux', 'Javascript'],
  description: 'The Space-Travelers app is a single-page-app that gets information from the SpaceX API and shows you a list with some of their rockets and missions for you to reserve, join and watch at your profile page.',
  liveBtn: 'https://salty-coast-56792.herokuapp.com/',
  sourceBtn: 'https://github.com/ulisesedu7/microverse-space-travelers',
},
{
  id: 1,
  featureImg: 'images/project-img2.png',
  projectName: 'Math Magicians',
  technologies: ['HTML', 'CSS', 'Javascript', 'React'],
  description: 'This small web application built with React.js helps you with small calculations, a simple calculator that proves just how powerful and easy can React be when creating single-page-apps.',
  liveBtn: 'https://mysterious-bayou-66250.herokuapp.com/',
  sourceBtn: 'https://github.com/ulisesedu7/Math-Magicians',
},
{
  id: 2,
  featureImg: 'images/project-img3.png',
  projectName: 'Budget Tracker App',
  technologies: ['Ruby on Rails', 'PostgreSQL', 'HTML', 'CSS', 'Bootstrap'],
  description: 'A Full-Stack Mobile app that will help you keep track of all the purchases you make day a day. You can create categories and add the payments to individual categories to better manage your budget.',
  liveBtn: 'https://agile-woodland-68434.herokuapp.com/',
  sourceBtn: 'https://github.com/ulisesedu7/budget-app',
},
{
  id: 3,
  featureImg: 'images/project-img4.png',
  projectName: 'To Do List',
  technologies: ['HTML', 'CSS', 'Javascript', 'WebPack'],
  description: 'With this To-Do-List built mainly with javascript (and some HTML & CSS) you will be able to add, remove, edit tasks for your daily basis and once you complete them, you can mark them so and clear the list.',
  liveBtn: 'https://ulisesedu7.github.io/To-Do-List-Project/',
  sourceBtn: 'https://github.com/ulisesedu7/To-Do-List-Project',
},
{
  id: 4,
  featureImg: 'images/project-img5.png',
  projectName: 'TV Shows',
  technologies: ['Javascript', 'HTML', 'CSS', 'Webpack'],
  description: 'This is a single-page web application that displays shows, lets you add likes, and uses a pop-up window to display more information about them, like their release dates and stuff (also you can add comments).',
  liveBtn: 'https://ulisesedu7.github.io/CapstoneProject2/',
  sourceBtn: 'https://github.com/ulisesedu7/CapstoneProject2',
},
{
  id: 5,
  featureImg: 'images/project-img6.png',
  projectName: 'Tchaikovsky Piano Concert',
  technologies: ['HTML', 'CSS', 'Javascript'],
  description: 'Check this landing page created with HTML, CSS & Javascript for a Classical Piano Concert, it will give you all the information you need to know about it and motivate you to be a attend it.',
  liveBtn: 'https://ulisesedu7.github.io/Capstone-Project-1/',
  sourceBtn: 'https://github.com/ulisesedu7/Capstone-Project-1',
}];

export default projectInfo;